// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: yandex/cloud/iot/devices/v1/registry_service.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Yandex.Cloud.Iot.Devices.V1 {
  /// <summary>
  /// A set of methods for managing registry.
  /// </summary>
  internal static partial class RegistryService
  {
    static readonly string __ServiceName = "yandex.cloud.iot.devices.v1.RegistryService";

    static readonly grpc::Marshaller<global::Yandex.Cloud.Iot.Devices.V1.GetRegistryRequest> __Marshaller_yandex_cloud_iot_devices_v1_GetRegistryRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Yandex.Cloud.Iot.Devices.V1.GetRegistryRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Yandex.Cloud.Iot.Devices.V1.Registry> __Marshaller_yandex_cloud_iot_devices_v1_Registry = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Yandex.Cloud.Iot.Devices.V1.Registry.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Yandex.Cloud.Iot.Devices.V1.ListRegistriesRequest> __Marshaller_yandex_cloud_iot_devices_v1_ListRegistriesRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Yandex.Cloud.Iot.Devices.V1.ListRegistriesRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Yandex.Cloud.Iot.Devices.V1.ListRegistriesResponse> __Marshaller_yandex_cloud_iot_devices_v1_ListRegistriesResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Yandex.Cloud.Iot.Devices.V1.ListRegistriesResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Yandex.Cloud.Iot.Devices.V1.CreateRegistryRequest> __Marshaller_yandex_cloud_iot_devices_v1_CreateRegistryRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Yandex.Cloud.Iot.Devices.V1.CreateRegistryRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Yandex.Cloud.Operation.Operation> __Marshaller_yandex_cloud_operation_Operation = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Yandex.Cloud.Operation.Operation.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Yandex.Cloud.Iot.Devices.V1.UpdateRegistryRequest> __Marshaller_yandex_cloud_iot_devices_v1_UpdateRegistryRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Yandex.Cloud.Iot.Devices.V1.UpdateRegistryRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Yandex.Cloud.Iot.Devices.V1.DeleteRegistryRequest> __Marshaller_yandex_cloud_iot_devices_v1_DeleteRegistryRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Yandex.Cloud.Iot.Devices.V1.DeleteRegistryRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Yandex.Cloud.Iot.Devices.V1.ListRegistryCertificatesRequest> __Marshaller_yandex_cloud_iot_devices_v1_ListRegistryCertificatesRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Yandex.Cloud.Iot.Devices.V1.ListRegistryCertificatesRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Yandex.Cloud.Iot.Devices.V1.ListRegistryCertificatesResponse> __Marshaller_yandex_cloud_iot_devices_v1_ListRegistryCertificatesResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Yandex.Cloud.Iot.Devices.V1.ListRegistryCertificatesResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Yandex.Cloud.Iot.Devices.V1.AddRegistryCertificateRequest> __Marshaller_yandex_cloud_iot_devices_v1_AddRegistryCertificateRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Yandex.Cloud.Iot.Devices.V1.AddRegistryCertificateRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Yandex.Cloud.Iot.Devices.V1.DeleteRegistryCertificateRequest> __Marshaller_yandex_cloud_iot_devices_v1_DeleteRegistryCertificateRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Yandex.Cloud.Iot.Devices.V1.DeleteRegistryCertificateRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Yandex.Cloud.Iot.Devices.V1.ListRegistryPasswordsRequest> __Marshaller_yandex_cloud_iot_devices_v1_ListRegistryPasswordsRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Yandex.Cloud.Iot.Devices.V1.ListRegistryPasswordsRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Yandex.Cloud.Iot.Devices.V1.ListRegistryPasswordsResponse> __Marshaller_yandex_cloud_iot_devices_v1_ListRegistryPasswordsResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Yandex.Cloud.Iot.Devices.V1.ListRegistryPasswordsResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Yandex.Cloud.Iot.Devices.V1.AddRegistryPasswordRequest> __Marshaller_yandex_cloud_iot_devices_v1_AddRegistryPasswordRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Yandex.Cloud.Iot.Devices.V1.AddRegistryPasswordRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Yandex.Cloud.Iot.Devices.V1.DeleteRegistryPasswordRequest> __Marshaller_yandex_cloud_iot_devices_v1_DeleteRegistryPasswordRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Yandex.Cloud.Iot.Devices.V1.DeleteRegistryPasswordRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Yandex.Cloud.Iot.Devices.V1.ListDeviceTopicAliasesRequest> __Marshaller_yandex_cloud_iot_devices_v1_ListDeviceTopicAliasesRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Yandex.Cloud.Iot.Devices.V1.ListDeviceTopicAliasesRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Yandex.Cloud.Iot.Devices.V1.ListDeviceTopicAliasesResponse> __Marshaller_yandex_cloud_iot_devices_v1_ListDeviceTopicAliasesResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Yandex.Cloud.Iot.Devices.V1.ListDeviceTopicAliasesResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Yandex.Cloud.Iot.Devices.V1.ListRegistryOperationsRequest> __Marshaller_yandex_cloud_iot_devices_v1_ListRegistryOperationsRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Yandex.Cloud.Iot.Devices.V1.ListRegistryOperationsRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Yandex.Cloud.Iot.Devices.V1.ListRegistryOperationsResponse> __Marshaller_yandex_cloud_iot_devices_v1_ListRegistryOperationsResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Yandex.Cloud.Iot.Devices.V1.ListRegistryOperationsResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::Yandex.Cloud.Iot.Devices.V1.GetRegistryRequest, global::Yandex.Cloud.Iot.Devices.V1.Registry> __Method_Get = new grpc::Method<global::Yandex.Cloud.Iot.Devices.V1.GetRegistryRequest, global::Yandex.Cloud.Iot.Devices.V1.Registry>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Get",
        __Marshaller_yandex_cloud_iot_devices_v1_GetRegistryRequest,
        __Marshaller_yandex_cloud_iot_devices_v1_Registry);

    static readonly grpc::Method<global::Yandex.Cloud.Iot.Devices.V1.ListRegistriesRequest, global::Yandex.Cloud.Iot.Devices.V1.ListRegistriesResponse> __Method_List = new grpc::Method<global::Yandex.Cloud.Iot.Devices.V1.ListRegistriesRequest, global::Yandex.Cloud.Iot.Devices.V1.ListRegistriesResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "List",
        __Marshaller_yandex_cloud_iot_devices_v1_ListRegistriesRequest,
        __Marshaller_yandex_cloud_iot_devices_v1_ListRegistriesResponse);

    static readonly grpc::Method<global::Yandex.Cloud.Iot.Devices.V1.CreateRegistryRequest, global::Yandex.Cloud.Operation.Operation> __Method_Create = new grpc::Method<global::Yandex.Cloud.Iot.Devices.V1.CreateRegistryRequest, global::Yandex.Cloud.Operation.Operation>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Create",
        __Marshaller_yandex_cloud_iot_devices_v1_CreateRegistryRequest,
        __Marshaller_yandex_cloud_operation_Operation);

    static readonly grpc::Method<global::Yandex.Cloud.Iot.Devices.V1.UpdateRegistryRequest, global::Yandex.Cloud.Operation.Operation> __Method_Update = new grpc::Method<global::Yandex.Cloud.Iot.Devices.V1.UpdateRegistryRequest, global::Yandex.Cloud.Operation.Operation>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Update",
        __Marshaller_yandex_cloud_iot_devices_v1_UpdateRegistryRequest,
        __Marshaller_yandex_cloud_operation_Operation);

    static readonly grpc::Method<global::Yandex.Cloud.Iot.Devices.V1.DeleteRegistryRequest, global::Yandex.Cloud.Operation.Operation> __Method_Delete = new grpc::Method<global::Yandex.Cloud.Iot.Devices.V1.DeleteRegistryRequest, global::Yandex.Cloud.Operation.Operation>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Delete",
        __Marshaller_yandex_cloud_iot_devices_v1_DeleteRegistryRequest,
        __Marshaller_yandex_cloud_operation_Operation);

    static readonly grpc::Method<global::Yandex.Cloud.Iot.Devices.V1.ListRegistryCertificatesRequest, global::Yandex.Cloud.Iot.Devices.V1.ListRegistryCertificatesResponse> __Method_ListCertificates = new grpc::Method<global::Yandex.Cloud.Iot.Devices.V1.ListRegistryCertificatesRequest, global::Yandex.Cloud.Iot.Devices.V1.ListRegistryCertificatesResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ListCertificates",
        __Marshaller_yandex_cloud_iot_devices_v1_ListRegistryCertificatesRequest,
        __Marshaller_yandex_cloud_iot_devices_v1_ListRegistryCertificatesResponse);

    static readonly grpc::Method<global::Yandex.Cloud.Iot.Devices.V1.AddRegistryCertificateRequest, global::Yandex.Cloud.Operation.Operation> __Method_AddCertificate = new grpc::Method<global::Yandex.Cloud.Iot.Devices.V1.AddRegistryCertificateRequest, global::Yandex.Cloud.Operation.Operation>(
        grpc::MethodType.Unary,
        __ServiceName,
        "AddCertificate",
        __Marshaller_yandex_cloud_iot_devices_v1_AddRegistryCertificateRequest,
        __Marshaller_yandex_cloud_operation_Operation);

    static readonly grpc::Method<global::Yandex.Cloud.Iot.Devices.V1.DeleteRegistryCertificateRequest, global::Yandex.Cloud.Operation.Operation> __Method_DeleteCertificate = new grpc::Method<global::Yandex.Cloud.Iot.Devices.V1.DeleteRegistryCertificateRequest, global::Yandex.Cloud.Operation.Operation>(
        grpc::MethodType.Unary,
        __ServiceName,
        "DeleteCertificate",
        __Marshaller_yandex_cloud_iot_devices_v1_DeleteRegistryCertificateRequest,
        __Marshaller_yandex_cloud_operation_Operation);

    static readonly grpc::Method<global::Yandex.Cloud.Iot.Devices.V1.ListRegistryPasswordsRequest, global::Yandex.Cloud.Iot.Devices.V1.ListRegistryPasswordsResponse> __Method_ListPasswords = new grpc::Method<global::Yandex.Cloud.Iot.Devices.V1.ListRegistryPasswordsRequest, global::Yandex.Cloud.Iot.Devices.V1.ListRegistryPasswordsResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ListPasswords",
        __Marshaller_yandex_cloud_iot_devices_v1_ListRegistryPasswordsRequest,
        __Marshaller_yandex_cloud_iot_devices_v1_ListRegistryPasswordsResponse);

    static readonly grpc::Method<global::Yandex.Cloud.Iot.Devices.V1.AddRegistryPasswordRequest, global::Yandex.Cloud.Operation.Operation> __Method_AddPassword = new grpc::Method<global::Yandex.Cloud.Iot.Devices.V1.AddRegistryPasswordRequest, global::Yandex.Cloud.Operation.Operation>(
        grpc::MethodType.Unary,
        __ServiceName,
        "AddPassword",
        __Marshaller_yandex_cloud_iot_devices_v1_AddRegistryPasswordRequest,
        __Marshaller_yandex_cloud_operation_Operation);

    static readonly grpc::Method<global::Yandex.Cloud.Iot.Devices.V1.DeleteRegistryPasswordRequest, global::Yandex.Cloud.Operation.Operation> __Method_DeletePassword = new grpc::Method<global::Yandex.Cloud.Iot.Devices.V1.DeleteRegistryPasswordRequest, global::Yandex.Cloud.Operation.Operation>(
        grpc::MethodType.Unary,
        __ServiceName,
        "DeletePassword",
        __Marshaller_yandex_cloud_iot_devices_v1_DeleteRegistryPasswordRequest,
        __Marshaller_yandex_cloud_operation_Operation);

    static readonly grpc::Method<global::Yandex.Cloud.Iot.Devices.V1.ListDeviceTopicAliasesRequest, global::Yandex.Cloud.Iot.Devices.V1.ListDeviceTopicAliasesResponse> __Method_ListDeviceTopicAliases = new grpc::Method<global::Yandex.Cloud.Iot.Devices.V1.ListDeviceTopicAliasesRequest, global::Yandex.Cloud.Iot.Devices.V1.ListDeviceTopicAliasesResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ListDeviceTopicAliases",
        __Marshaller_yandex_cloud_iot_devices_v1_ListDeviceTopicAliasesRequest,
        __Marshaller_yandex_cloud_iot_devices_v1_ListDeviceTopicAliasesResponse);

    static readonly grpc::Method<global::Yandex.Cloud.Iot.Devices.V1.ListRegistryOperationsRequest, global::Yandex.Cloud.Iot.Devices.V1.ListRegistryOperationsResponse> __Method_ListOperations = new grpc::Method<global::Yandex.Cloud.Iot.Devices.V1.ListRegistryOperationsRequest, global::Yandex.Cloud.Iot.Devices.V1.ListRegistryOperationsResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ListOperations",
        __Marshaller_yandex_cloud_iot_devices_v1_ListRegistryOperationsRequest,
        __Marshaller_yandex_cloud_iot_devices_v1_ListRegistryOperationsResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Yandex.Cloud.Iot.Devices.V1.RegistryServiceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Client for RegistryService</summary>
    public partial class RegistryServiceClient : grpc::ClientBase<RegistryServiceClient>
    {
      /// <summary>Creates a new client for RegistryService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public RegistryServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for RegistryService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public RegistryServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected RegistryServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected RegistryServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      /// Returns the specified registry.
      ///
      /// To get the list of available registries, make a [List] request.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Yandex.Cloud.Iot.Devices.V1.Registry Get(global::Yandex.Cloud.Iot.Devices.V1.GetRegistryRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Get(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Returns the specified registry.
      ///
      /// To get the list of available registries, make a [List] request.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Yandex.Cloud.Iot.Devices.V1.Registry Get(global::Yandex.Cloud.Iot.Devices.V1.GetRegistryRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Get, null, options, request);
      }
      /// <summary>
      /// Returns the specified registry.
      ///
      /// To get the list of available registries, make a [List] request.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Yandex.Cloud.Iot.Devices.V1.Registry> GetAsync(global::Yandex.Cloud.Iot.Devices.V1.GetRegistryRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Returns the specified registry.
      ///
      /// To get the list of available registries, make a [List] request.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Yandex.Cloud.Iot.Devices.V1.Registry> GetAsync(global::Yandex.Cloud.Iot.Devices.V1.GetRegistryRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Get, null, options, request);
      }
      /// <summary>
      /// Retrieves the list of registries in the specified folder.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Yandex.Cloud.Iot.Devices.V1.ListRegistriesResponse List(global::Yandex.Cloud.Iot.Devices.V1.ListRegistriesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return List(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Retrieves the list of registries in the specified folder.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Yandex.Cloud.Iot.Devices.V1.ListRegistriesResponse List(global::Yandex.Cloud.Iot.Devices.V1.ListRegistriesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_List, null, options, request);
      }
      /// <summary>
      /// Retrieves the list of registries in the specified folder.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Yandex.Cloud.Iot.Devices.V1.ListRegistriesResponse> ListAsync(global::Yandex.Cloud.Iot.Devices.V1.ListRegistriesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ListAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Retrieves the list of registries in the specified folder.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Yandex.Cloud.Iot.Devices.V1.ListRegistriesResponse> ListAsync(global::Yandex.Cloud.Iot.Devices.V1.ListRegistriesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_List, null, options, request);
      }
      /// <summary>
      /// Creates a registry in the specified folder.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Yandex.Cloud.Operation.Operation Create(global::Yandex.Cloud.Iot.Devices.V1.CreateRegistryRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Create(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Creates a registry in the specified folder.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Yandex.Cloud.Operation.Operation Create(global::Yandex.Cloud.Iot.Devices.V1.CreateRegistryRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Create, null, options, request);
      }
      /// <summary>
      /// Creates a registry in the specified folder.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Yandex.Cloud.Operation.Operation> CreateAsync(global::Yandex.Cloud.Iot.Devices.V1.CreateRegistryRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Creates a registry in the specified folder.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Yandex.Cloud.Operation.Operation> CreateAsync(global::Yandex.Cloud.Iot.Devices.V1.CreateRegistryRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Create, null, options, request);
      }
      /// <summary>
      /// Updates the specified registry.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Yandex.Cloud.Operation.Operation Update(global::Yandex.Cloud.Iot.Devices.V1.UpdateRegistryRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Update(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Updates the specified registry.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Yandex.Cloud.Operation.Operation Update(global::Yandex.Cloud.Iot.Devices.V1.UpdateRegistryRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Update, null, options, request);
      }
      /// <summary>
      /// Updates the specified registry.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Yandex.Cloud.Operation.Operation> UpdateAsync(global::Yandex.Cloud.Iot.Devices.V1.UpdateRegistryRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdateAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Updates the specified registry.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Yandex.Cloud.Operation.Operation> UpdateAsync(global::Yandex.Cloud.Iot.Devices.V1.UpdateRegistryRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Update, null, options, request);
      }
      /// <summary>
      /// Deletes the specified registry.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Yandex.Cloud.Operation.Operation Delete(global::Yandex.Cloud.Iot.Devices.V1.DeleteRegistryRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Delete(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Deletes the specified registry.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Yandex.Cloud.Operation.Operation Delete(global::Yandex.Cloud.Iot.Devices.V1.DeleteRegistryRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Delete, null, options, request);
      }
      /// <summary>
      /// Deletes the specified registry.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Yandex.Cloud.Operation.Operation> DeleteAsync(global::Yandex.Cloud.Iot.Devices.V1.DeleteRegistryRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Deletes the specified registry.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Yandex.Cloud.Operation.Operation> DeleteAsync(global::Yandex.Cloud.Iot.Devices.V1.DeleteRegistryRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Delete, null, options, request);
      }
      /// <summary>
      /// Retrieves the list of registry certificates for the specified registry.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Yandex.Cloud.Iot.Devices.V1.ListRegistryCertificatesResponse ListCertificates(global::Yandex.Cloud.Iot.Devices.V1.ListRegistryCertificatesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ListCertificates(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Retrieves the list of registry certificates for the specified registry.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Yandex.Cloud.Iot.Devices.V1.ListRegistryCertificatesResponse ListCertificates(global::Yandex.Cloud.Iot.Devices.V1.ListRegistryCertificatesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ListCertificates, null, options, request);
      }
      /// <summary>
      /// Retrieves the list of registry certificates for the specified registry.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Yandex.Cloud.Iot.Devices.V1.ListRegistryCertificatesResponse> ListCertificatesAsync(global::Yandex.Cloud.Iot.Devices.V1.ListRegistryCertificatesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ListCertificatesAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Retrieves the list of registry certificates for the specified registry.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Yandex.Cloud.Iot.Devices.V1.ListRegistryCertificatesResponse> ListCertificatesAsync(global::Yandex.Cloud.Iot.Devices.V1.ListRegistryCertificatesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ListCertificates, null, options, request);
      }
      /// <summary>
      /// Adds a certificate.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Yandex.Cloud.Operation.Operation AddCertificate(global::Yandex.Cloud.Iot.Devices.V1.AddRegistryCertificateRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AddCertificate(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Adds a certificate.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Yandex.Cloud.Operation.Operation AddCertificate(global::Yandex.Cloud.Iot.Devices.V1.AddRegistryCertificateRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_AddCertificate, null, options, request);
      }
      /// <summary>
      /// Adds a certificate.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Yandex.Cloud.Operation.Operation> AddCertificateAsync(global::Yandex.Cloud.Iot.Devices.V1.AddRegistryCertificateRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AddCertificateAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Adds a certificate.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Yandex.Cloud.Operation.Operation> AddCertificateAsync(global::Yandex.Cloud.Iot.Devices.V1.AddRegistryCertificateRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_AddCertificate, null, options, request);
      }
      /// <summary>
      /// Deletes the specified registry certificate.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Yandex.Cloud.Operation.Operation DeleteCertificate(global::Yandex.Cloud.Iot.Devices.V1.DeleteRegistryCertificateRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteCertificate(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Deletes the specified registry certificate.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Yandex.Cloud.Operation.Operation DeleteCertificate(global::Yandex.Cloud.Iot.Devices.V1.DeleteRegistryCertificateRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_DeleteCertificate, null, options, request);
      }
      /// <summary>
      /// Deletes the specified registry certificate.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Yandex.Cloud.Operation.Operation> DeleteCertificateAsync(global::Yandex.Cloud.Iot.Devices.V1.DeleteRegistryCertificateRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteCertificateAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Deletes the specified registry certificate.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Yandex.Cloud.Operation.Operation> DeleteCertificateAsync(global::Yandex.Cloud.Iot.Devices.V1.DeleteRegistryCertificateRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_DeleteCertificate, null, options, request);
      }
      /// <summary>
      /// Retrieves the list of passwords for the specified registry.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Yandex.Cloud.Iot.Devices.V1.ListRegistryPasswordsResponse ListPasswords(global::Yandex.Cloud.Iot.Devices.V1.ListRegistryPasswordsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ListPasswords(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Retrieves the list of passwords for the specified registry.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Yandex.Cloud.Iot.Devices.V1.ListRegistryPasswordsResponse ListPasswords(global::Yandex.Cloud.Iot.Devices.V1.ListRegistryPasswordsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ListPasswords, null, options, request);
      }
      /// <summary>
      /// Retrieves the list of passwords for the specified registry.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Yandex.Cloud.Iot.Devices.V1.ListRegistryPasswordsResponse> ListPasswordsAsync(global::Yandex.Cloud.Iot.Devices.V1.ListRegistryPasswordsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ListPasswordsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Retrieves the list of passwords for the specified registry.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Yandex.Cloud.Iot.Devices.V1.ListRegistryPasswordsResponse> ListPasswordsAsync(global::Yandex.Cloud.Iot.Devices.V1.ListRegistryPasswordsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ListPasswords, null, options, request);
      }
      /// <summary>
      /// Adds password for the specified registry.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Yandex.Cloud.Operation.Operation AddPassword(global::Yandex.Cloud.Iot.Devices.V1.AddRegistryPasswordRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AddPassword(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Adds password for the specified registry.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Yandex.Cloud.Operation.Operation AddPassword(global::Yandex.Cloud.Iot.Devices.V1.AddRegistryPasswordRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_AddPassword, null, options, request);
      }
      /// <summary>
      /// Adds password for the specified registry.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Yandex.Cloud.Operation.Operation> AddPasswordAsync(global::Yandex.Cloud.Iot.Devices.V1.AddRegistryPasswordRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AddPasswordAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Adds password for the specified registry.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Yandex.Cloud.Operation.Operation> AddPasswordAsync(global::Yandex.Cloud.Iot.Devices.V1.AddRegistryPasswordRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_AddPassword, null, options, request);
      }
      /// <summary>
      /// Deletes the specified password.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Yandex.Cloud.Operation.Operation DeletePassword(global::Yandex.Cloud.Iot.Devices.V1.DeleteRegistryPasswordRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeletePassword(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Deletes the specified password.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Yandex.Cloud.Operation.Operation DeletePassword(global::Yandex.Cloud.Iot.Devices.V1.DeleteRegistryPasswordRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_DeletePassword, null, options, request);
      }
      /// <summary>
      /// Deletes the specified password.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Yandex.Cloud.Operation.Operation> DeletePasswordAsync(global::Yandex.Cloud.Iot.Devices.V1.DeleteRegistryPasswordRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeletePasswordAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Deletes the specified password.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Yandex.Cloud.Operation.Operation> DeletePasswordAsync(global::Yandex.Cloud.Iot.Devices.V1.DeleteRegistryPasswordRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_DeletePassword, null, options, request);
      }
      /// <summary>
      /// Retrieves the list of device topic aliases for the specified registry.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Yandex.Cloud.Iot.Devices.V1.ListDeviceTopicAliasesResponse ListDeviceTopicAliases(global::Yandex.Cloud.Iot.Devices.V1.ListDeviceTopicAliasesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ListDeviceTopicAliases(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Retrieves the list of device topic aliases for the specified registry.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Yandex.Cloud.Iot.Devices.V1.ListDeviceTopicAliasesResponse ListDeviceTopicAliases(global::Yandex.Cloud.Iot.Devices.V1.ListDeviceTopicAliasesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ListDeviceTopicAliases, null, options, request);
      }
      /// <summary>
      /// Retrieves the list of device topic aliases for the specified registry.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Yandex.Cloud.Iot.Devices.V1.ListDeviceTopicAliasesResponse> ListDeviceTopicAliasesAsync(global::Yandex.Cloud.Iot.Devices.V1.ListDeviceTopicAliasesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ListDeviceTopicAliasesAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Retrieves the list of device topic aliases for the specified registry.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Yandex.Cloud.Iot.Devices.V1.ListDeviceTopicAliasesResponse> ListDeviceTopicAliasesAsync(global::Yandex.Cloud.Iot.Devices.V1.ListDeviceTopicAliasesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ListDeviceTopicAliases, null, options, request);
      }
      /// <summary>
      /// Lists operations for the specified registry.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Yandex.Cloud.Iot.Devices.V1.ListRegistryOperationsResponse ListOperations(global::Yandex.Cloud.Iot.Devices.V1.ListRegistryOperationsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ListOperations(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Lists operations for the specified registry.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Yandex.Cloud.Iot.Devices.V1.ListRegistryOperationsResponse ListOperations(global::Yandex.Cloud.Iot.Devices.V1.ListRegistryOperationsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ListOperations, null, options, request);
      }
      /// <summary>
      /// Lists operations for the specified registry.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Yandex.Cloud.Iot.Devices.V1.ListRegistryOperationsResponse> ListOperationsAsync(global::Yandex.Cloud.Iot.Devices.V1.ListRegistryOperationsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ListOperationsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Lists operations for the specified registry.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Yandex.Cloud.Iot.Devices.V1.ListRegistryOperationsResponse> ListOperationsAsync(global::Yandex.Cloud.Iot.Devices.V1.ListRegistryOperationsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ListOperations, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override RegistryServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new RegistryServiceClient(configuration);
      }
    }

  }
}
#endregion
